name: Update App

on:
 push:
   branches: [main]

permissions:
  contents: read

jobs:
 deploy-app:
   runs-on: fedora-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       with:
         token: ${{ secrets.DO_PAT }}
